In [1]:
import numpy as np

In [2]:
one = np.ones((3,4))

In [3]:
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
one = np.ones_like(np.arange(10).reshape((5,2)))

In [7]:
one

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [8]:
m = np.arange(10).reshape((2,5))

In [9]:
m.dtype

dtype('int64')

In [12]:
m[0,0] = 1.0
m

array([[1, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
m.dtype

dtype('int64')

In [16]:
m[0,0] = 1.2
m

array([[1, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
boo = np.array(np.arange(10), dtype = "?")

In [19]:
boo

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [26]:
com = np.array([[1 + 2j, 3 + 1j], [0 + 0.5j, 3 + 2j]], dtype = 'c8')

In [27]:
com

array([[1.+2.j , 3.+1.j ],
       [0.+0.5j, 3.+2.j ]], dtype=complex64)

In [28]:
fm = m.astype(np.float64)

In [29]:
fm

array([[1., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [30]:
fm[0,0]=1.2

In [32]:
fm

array([[1.2, 1. , 2. , 3. , 4. ],
       [5. , 6. , 7. , 8. , 9. ]])

In [33]:
sm = np.array([['1.2','3.1','2.55'],['9.0','3.4','4.6']])

In [34]:
sm

array([['1.2', '3.1', '2.55'],
       ['9.0', '3.4', '4.6']], dtype='<U4')

In [35]:
nm = sm.astype(np.float32)

In [36]:
nm

array([[1.2 , 3.1 , 2.55],
       [9.  , 3.4 , 4.6 ]], dtype=float32)

In [42]:
#copy arr
arr = np.arange(10).reshape(5,2)
carr = arr.copy()
carr[0,0] = 5

In [43]:
print(arr)
print(carr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[5 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [63]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [47]:
from IPython.display import Markdown, display

In [48]:
arr2 = np.array([[10, 20, 30],[40, 50, 60]])

In [65]:
display(Markdown(f"""### '+, -, /, *' are all element-wise operation in NumPy\n
`arr1` = {arr1}, `arr2` = {arr2}\n
`arr1` * `arr2` = {arr1 * arr2}\n
`arr1` / `arr2` = {arr1 / arr2}\n
`arr1` + `arr2` = {arr1 + arr2}\n
`arr1` - `arr2` = {arr1 - arr2}\n"""))


### '+, -, /, *' are all element-wise operation in NumPy

`arr1` = [[1 2 3]
 [4 5 6]], `arr2` = [[10 20 30]
 [40 50 60]]

`arr1` * `arr2` = [[ 10  40  90]
 [160 250 360]]

`arr1` / `arr2` = [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]

`arr1` + `arr2` = [[11 22 33]
 [44 55 66]]

`arr1` - `arr2` = [[ -9 -18 -27]
 [-36 -45 -54]]


In [66]:
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [67]:
comparison = arr1 < arr2

In [68]:
comparison

array([[ True,  True,  True],
       [ True,  True,  True]])

In [69]:
arr = np.arange(10)

In [70]:
arr[5]

np.int64(5)

In [71]:
arr[5:8]

array([5, 6, 7])

In [72]:
arr[1:3] = 10
arr

array([ 0, 10, 10,  3,  4,  5,  6,  7,  8,  9])

In [74]:
part = arr[0:3]

In [75]:
part

array([ 0, 10, 10])

In [76]:
part[:] = 11

In [77]:
arr

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9])

In [78]:
part = arr[:3].copy()

In [79]:
part

array([11, 11, 11])

In [80]:
arr

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9])

In [81]:
part[:] = 100

In [82]:
part

array([100, 100, 100])

In [83]:
arr

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9])

In [85]:
rerm = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [86]:
rerm

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [87]:
rerm[0,0]

np.int64(1)

In [88]:
rerm[0,1]

np.int64(2)

In [89]:
rerm[0]

array([1, 2, 3])

In [90]:
rerm[2]

array([1, 2, 3])

In [91]:
arr = np.arange(9).reshape((3,3))

In [92]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
arr[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [94]:
arr[:2][1:]

array([[3, 4, 5]])

In [95]:
arr[1,2]

np.int64(5)

In [96]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [97]:
lower_dim_slice = arr[1, :2]

In [98]:
lower_dim_slice

array([3, 4])

In [99]:
lower_dim_slice.shape

(2,)

In [100]:
arr[:2, 2]

array([2, 5])

In [101]:
arr[:2,2].shape

(2,)

In [102]:
arr[:2, 1]

array([1, 4])

In [108]:
boolm = np.array([[10, 20, 19, 20, 12, 25, 20, 17]])
boo = boolm < 18
display(Markdown(f"""### Boolean ndarray\n
Comparison with ndarray will yields boolean ndarray\n
`boolm` < 18 yields {boo}"""))

### Boolean ndarray

Comparison with ndarray will yields boolean ndarray

`boolm` < 18 yields [[ True False False False  True False False  True]]

In [9]:
import numpy as np
from IPython.display import display, Markdown
names = np.array(["Bob", "Alice", "Lucy", "Bob", "John", "Bob"])

In [3]:
data = np.array([[4,7],[1,2],[-4,5],[3,1],[5, 6], [7, 5]])

In [4]:
bobrows = names == "Bob"

In [5]:
bobrows

array([ True, False, False,  True, False,  True])

In [6]:
data[bobrows]

array([[4, 7],
       [3, 1],
       [7, 5]])

In [11]:
display(Markdown(f"""### Use boolean ndarray to get rows\n
`names` = {names}, `data` = {data}\n
'bobrows' = `name` == "Bob" (Which is {bobrows}\n
then `data[bobrows]` = {data[bobrows]}"""))

### Use boolean ndarray to get rows

`names` = ['Bob' 'Alice' 'Lucy' 'Bob' 'John' 'Bob'], `data` = [[ 4  7]
 [ 1  2]
 [-4  5]
 [ 3  1]
 [ 5  6]
 [ 7  5]]

'bobrows' = `name` == "Bob" (Which is [ True False False  True False  True]

then `data[bobrows]` = [[4 7]
 [3 1]
 [7 5]]